"""TAG to RULE mapping for enrichment routing"""

TAG_TO_RULE = {
    "Bloomberg": "newsbrief_with_links",
    "WSJ": "newsbrief_with_links",
    "Financial Times / FT": "newsbrief_with_links",
    "Financial Times": "newsbrief_with_links",
    "FT": "newsbrief_with_links",
    "Reuters": "newsbrief_with_links",
    "Business Insider": "newsbrief_with_links",
    "Estad\u00e3o": "newsbrief_with_links",
    "Folha": "newsbrief_with_links",
    "Barron's Daily": "newsbrief_with_links",
    "Barons Daily": "newsbrief_with_links",
    "Topdown Charts": "newsbrief_with_links",
    "O Globo": "newsbrief_with_links",
    "TKer": "newsbrief_with_links",
    "Macro Mornings": "newsbrief_with_links",
    "Paul Gigot WSJ": "newsbrief_with_links",
    "Rosenberg_EM": "rosenberg_deep_research",
    "Rosenberg Research": "breakfast_headlines",
    "John Cochrane": "cochrane_detailed",
    "Adam Tooze": "gold_standard_enhanced",
    "Goldman Sachs": "gold_standard_enhanced",
    "Torsten Slok": "gold_standard_enhanced",
    "MacroTourist": "gold_standard_enhanced",
    "Matt Stoller": "gold_standard_enhanced",
    "Mohamed El-Erian": "elerian_rep",
    "Noahpinion": "gold_standard_enhanced",
    "Yascha Mounk": "gold_standard_enhanced",
    "WSJ Opinion": "wsj_opinion",
    "Shadow Price Macro": "shadow_vlm",
    "Macro Charts": "charts_vlm",
    "ChartStorm": "charts_vlm",
    "Itau": "itau_daily",
    "Itau_FOMC": "itau_daily",
    "Itau_China": "itau_daily",
    "Itau_Europe": "itau_daily",
    "Itau_Brazil_Daily": "itau_daily",
    "Itau_Global": "itau_daily",
    "Itau_Cac": "itau_daily",
    # New additions - Oct 29, 2025
    "Tony Pasquariello": "tony_pasquariello",
    "Washington Post": "newsbrief_with_links",
    "Best of Econtwitter": "gold_standard_enhanced",
}